server:
  port: 8080
  
spring:
  application:
    name: customer
  datasource:
    username: 'microservices'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: true
      show-sql: 'true'